# Generated by Django 2.2.10 on 2020-06-19 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('RegNo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=50)),
                ('Year', models.CharField(max_length=50)),
                ('Condition', models.CharField(max_length=50)),
                ('Pic', models.ImageField(upload_to='pictures')),
                ('Mileage', models.IntegerField()),
                ('Fee', models.IntegerField()),
                ('Available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('Idno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=50)),
                ('Secondname', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('Idno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=50)),
                ('Secondname', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PickLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('Latitude', models.FloatField(max_length=20)),
                ('Longitude', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(max_length=50)),
                ('To', models.DateTimeField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('Charge', models.IntegerField()),
                ('Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiremobilindex.Car')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiremobilindex.Client')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiremobilindex.PickLoc')),
                ('Saler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiremobilindex.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='CarPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.ImageField(upload_to='pictures')),
                ('RegNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiremobilindex.Car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiremobilindex.Owner'),
        ),
    ]
