# Generated by Django 2.2.10 on 2020-06-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiremobilindex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Available',
            field=models.BooleanField(default=True),
        ),
    ]
