# Generated by Django 2.2.10 on 2020-06-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiremobilindex', '0004_car_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=50)),
                ('Body', models.TextField(max_length=50)),
                ('At', models.DateTimeField()),
                ('Title', models.CharField(max_length=50)),
            ],
        ),
    ]
