# Generated by Django 2.2.10 on 2020-07-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiremobilindex', '0007_auto_20200709_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickloc',
            name='City',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='pickloc',
            name='Description',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='pickloc',
            name='Name',
            field=models.CharField(max_length=70),
        ),
    ]
