# Generated by Django 2.2.10 on 2020-07-09 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiremobilindex', '0008_auto_20200709_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='Location',
        ),
        migrations.DeleteModel(
            name='PickLoc',
        ),
    ]
