# Generated by Django 2.2.10 on 2020-07-09 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiremobilindex', '0009_auto_20200709_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('Latitude', models.FloatField(max_length=20)),
                ('Longitude', models.FloatField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='Location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hiremobilindex.PickLoc'),
        ),
    ]
