# Generated by Django 2.2.10 on 2020-07-09 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiremobilindex', '0010_auto_20200709_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickloc',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='pickloc',
            name='Longitude',
        ),
        migrations.AddField(
            model_name='car',
            name='Location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hiremobilindex.PickLoc'),
        ),
        migrations.AlterField(
            model_name='pickloc',
            name='City',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='pickloc',
            name='Description',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='pickloc',
            name='Name',
            field=models.CharField(max_length=70),
        ),
    ]
