# Generated by Django 2.2.10 on 2020-07-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiremobilindex', '0011_auto_20200709_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='Location',
        ),
        migrations.AddField(
            model_name='pickloc',
            name='Latitude',
            field=models.FloatField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickloc',
            name='Longitude',
            field=models.FloatField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pickloc',
            name='City',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pickloc',
            name='Description',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pickloc',
            name='Name',
            field=models.CharField(max_length=20),
        ),
    ]
