# Generated by Django 2.2.10 on 2020-07-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiremobilindex', '0015_auto_20200709_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='Date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='deal',
            name='To',
            field=models.DateField(max_length=50),
        ),
    ]
