# Generated by Django 2.2.10 on 2020-07-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiremobilindex', '0016_auto_20200710_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deal',
            name='To',
            field=models.DateField(),
        ),
    ]
