# Generated by Django 2.2.10 on 2020-07-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiremobilindex', '0017_auto_20200710_1403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deal',
        ),
    ]
